services:

  fastapi:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    container_name: arboviroses-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - DUCKDB_PATH=/app/data/processed/arboviroses.duckdb
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.streamlit
    container_name: arboviroses-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - DUCKDB_PATH=/app/data/processed/arboviroses.duckdb
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - fastapi
    restart: unless-stopped

  mlflow:
    image: python:3.12-slim
    container_name: arboviroses-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      bash -c "pip install mlflow -q &&
               mlflow server
               --host 0.0.0.0
               --port 5000
               --backend-store-uri sqlite:///mlruns/mlflow.db
               --default-artifact-root /mlruns"
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: arboviroses-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.9.3-python3.12
    container_name: arboviroses-airflow
    ports:
      - "8080:8080"
    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=arboviroses2025
      - DUCKDB_PATH=/opt/airflow/data/processed/arboviroses.duckdb
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@arboviroses.br ; airflow webserver & airflow scheduler"
    restart: unless-stopped

volumes:
  minio_data: